name: pysal-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python =3.7
  - bokeh
  - pip
  - geopandas
  - descartes
  - folium
  - ipython
  - ipywidgets
  - jupyterlab
  - pysal
  - nbconvert
  - networkx
  - palettable
  - scikit-learn
  - seaborn
  - statsmodels
  - segregation
  - hvplot
  - holoviews
  - geoviews
  - libpysal
  - mapclassify
  - esda
  - watermark
  - rasterio
  - descartes
  - folium
  - cenpy
  - pip:
    - contextily
